The
callback
can
send
data
to
a
coroutine
which
can
send
it
along
again
if
needed
.
Not
sure
if
this
is
what
you
are
looking
for
but
your
question
made
me
think
of
coroutines
.
If
the
callback
execution
is
asynchronous
","
I'm
not
sure
what
would
happen
if
the
coroutine
wasn't
back
to
the
first
yield
and
the
callback
tries
to
send
it
something
","
it
might
throw
a
ValueError
:
generator
already
executing
exception
.
