Actually
this
is
issue
in
PyCharm
utrunner.py
who
runs
unittests
.
If
you
are
using
DDT
there
is
a
wrapper
@ddt
and
@data
-
it
is
responsible
for
creating
separate
tests
for
each
data
entry
.
In
the
background
these
tests
have
different
names
e.g
.
This
would
create
tests
named
:
-
test_print_1_1
-
test_print_2_2
When
you
try
to
run
one
test
from
the
class
(
Right
Click
->
Run
'
Unittest
test_print
'
)
PyCharm
has
a
problem
to
load
your
tests
print_1_1
","
print_2_2
as
it
is
trying
to
load
test_print
test
.
When
you
look
at
the
code
of
utrunner.py
:
and
you
will
debug
it
you
see
that
issue
.
Ok
.
So
my
fix
for
that
is
to
load
proper
tests
from
the
class
.
It
is
just
a
workaround
and
it
is
not
perfect
","
however
as
DDT
is
adding
a
TestCase
as
another
method
to
the
class
it
is
hard
to
find
a
different
way
to
detect
right
test
cases
than
comparing
by
string
.
So
instead
of
:
you
can
try
to
use
:
Checking
if
digit
is
found
after
the
main
name
is
a
workaround
to
exclude
similar
test
cases
:
test_print
test_print_another_case
But
of
course
it
would
not
exclude
cases
:
test_if_prints_1
test_if_prints_2
So
in
the
worst
case
","
if
we
haven't
got
a
good
name
convention
we
will
run
similar
tests
","
but
in
most
cases
it
should
just
work
for
you
.
