I
am
facing
a
strange
error
while
executing
a
python
code
.
The
following
code
is
a
small
snippet
of
the
python
code
I
am
executing
:
While
executing
samplecode.py
I
am
facing
an
error
showing
the
following
:
My
logging.py
which
contains
the
code
that
needs
to
be
imported
while
execution
.
The
following
is
the
code
:
we
can
see
that
the
class
Dynamic
is
created
yet
the
import error
is
thrown
.
The
strangest
thing
is
I
did
few
examples
of
importing
files
and
it
worked
well
.
I
have
tried
hard
but
still
cannot
figure
it
out
.
I
would
like
to
know
why
this
error
was
thrown
and
why
suddenly
for
this
and
not
in
previous
samples
?
